### PR TITLE
[Testing] a11y suite for testing

### LINKED ISSUE #512: [Testing] a11y tests
Is it possible to run accessibility tests via [accessibility-developer-tools](https://www.npmjs.com/package/accessibility-developer-tools)? Or any other framework that allows to test for a11y. Previously I was using web-component-tester which exposes `a11ySuite` function. This function accepts fixture to perform a test onto. I was looking for a way to build a plugin (?) that would help me with that but I am not sure where to start.

### PR DESCRIPTION
**Pull request by jarrodek**
Fixes #512 - accessibility tests for web components.
This PR adds axa tests via `accessibility-developer-tools`. It creates new helper function `a11ySuite` to be used to perform axa tests. It accepts 3 arguments: test name, template string or element instance to test, and optional list of rules to ignore.

Example use:

```js
import { a11ySuite } from '@open-wc/testing';

describe('<my-component>', () => {
  a11ySuite('Suite name', `Template string or element instance`, ['list of tests to ignore']);
});
```

### CODE REVIEW

**Comment by Westbrook** [comment]
Hi @jarrodek, thanks for this submission. After some conversation, we'd prefer that a11y testing move forward with the help of `axe-core` rather than `accessibility-developer-tools`. If you are interested in updating this PR with that preference, I'd be happy to review what you come up with. If not the conversation in #512 will be the basis for future additions in this area and we'd love to have your input on what we're planning there. Thanks, again!

**Comment by jarrodek** [comment]
Hey,
Sorry for late response. I will take a look into `axe-core`. I am using similar module already with my components and I am trying to standardize `@open-wc` in my organization. Or at least something based on it. I'll be happy to help with development.

**Comment by jarrodek** [comment]
I have updated the PR as suggested in https://github.com/open-wc/open-wc/issues/512#issuecomment-513746605

Now the a11y is a plugin used by `@open-wc/testing`. It provides interface for Assert and Should libraries to test for accessibility. The API is documented in `packages/testing-a11y`.

Please, let me know what you think.

**Comment by daKmoR** [comment]
uh that is super awesome 💪 

there were just some outdated files and master to master syncing is always annoying so I move it into a separate branch 👍 
I also renamed it to `chai-a11y-axe` as it's more general than just for web components 👍 

it is still under your name so please take a look at https://github.com/open-wc/open-wc/pull/620 and say if that is ok :)

also feel free to fork this branch and create your own branch and make an extra PR if there are more changes you wanna do 💪 

very nice work - thaaankkk you 🤗 

PS: closing this in favour of https://github.com/open-wc/open-wc/pull/620

**Pull request closed without merging**
