### PR TITLE
[WIP] feat(es-dev-server): add experimental hot module replacement

### PR DESCRIPTION
**Pull request by LarsDenBakker**
Fixes https://github.com/open-wc/open-wc/issues/787

### CODE REVIEW

**Comment by bennypowers** [comment]
is this only blocked on review?

**Comment by daKmoR** [comment]
as far as I can tell `custom-elements-hmr-polyfill` still needs some improvements before it's generally usable... especially a good "ReflowStrategy" as key... 

currently, it's basically a quicker reload... but not what people would expect for HMR... state would need to stay intact - developers are "spoiled" with how nice HMR works in react... so I guess anything less will not fly 🙈 

PS: definitely a good starting point but I think it needs more work before
PPS: imho it should be really close to what react does... e.g. do not register any real classes but proxy classes and if a reregister gets triggered then instead replace those proxy functions and trigger a connectedCallback/rerend - I think this will probably also need some smart way to only resend changed files (e.g. server needs a dependency graph to send all files possibly affected by a file change... )

**Comment by LarsDenBakker** [comment]
It does implement a proxy class actually, it just re renders through inner html by default. If a custom element base class supports it you can trigger a re render on all instances, but I dont think thats the reponsibility of this library.

**Comment by daKmoR** [comment]
you should know which element got updated right? e.g. which tag?

so you should be able to do something like this right?
```js
// beware mega psoido code :p
const toUpdateElements = deepQuerySelectorWhichPiercesShadowDom(tagToUpdate);
toUpdateElements.forEach(el => {
  // replace proxy function stuff
  el.disconnectedCallback();
  el.connectedCallback();
});
```

which should work for every web component be it LitElement or Stencil or ... right?

**Comment by LarsDenBakker** [comment]
That doesnt re run work in the constructor, which is a problem for LitElement and can be a problem for author code.

Because of the proxy we can keep a reference to all connected elements so thats good

**Comment by LarsDenBakker** [comment]
Closing this for now to avoid clutting the review lane, still working on it though.

**Pull request closed without merging**
