### PR TITLE
Feat/upgrade workbox

### PR DESCRIPTION
**Pull request by thepassle**
closes https://github.com/open-wc/open-wc/issues/1281

@daKmoR or @LarsDenBakker  can you make sure I didnt mess up the commits? 🙈

### CODE REVIEW

**Comment by daKmoR** [comment]
this will release
- building-rollup 1.x
- building-webpack 3.x

just so we are aware of it... everyone agrees?

**Comment by daKmoR** [comment]
Changelog will have those breaking changes in the list 👇

* **building-rollup:** workbox APIs injectManifest placeholder changed
If you're using , you'll have to change the placeholder for the manifest like so:

```js
// Before:
workbox.precaching.precacheAndRoute([]);

// After:
workbox.precaching.precacheAndRoute(self.__WB_MANIFEST);
```
* **building-rollup:** workbox API importWorkboxFrom has been removed
It will always create a local Workbox runtime bundle for you, so the importWorkboxFrom option no longer makes sense

**Comment by LarsDenBakker** [comment]
As discussed, let's merge this to a separate branch. We will combine it with other breaking changes, for rollup they're listed here: https://github.com/open-wc/open-wc/issues/1153

**Comment by thepassle** [comment]
not stale

**Comment by thepassle** [comment]
Shoo stale

**Comment by LarsDenBakker** [comment]
Closing this as it was included in another PR.

**Pull request closed without merging**
