### PR TITLE
chore: update html-minifier to html-minifier-terser

### PR DESCRIPTION
**Pull request by abdonrd**
Motivation: https://github.com/open-wc/open-wc/pull/1832#pullrequestreview-486640682

In the snapshoots just remove a few extra `;`.

### CODE REVIEW

**Review by Westbrook — APPROVED** [review]
LGTM.

**Comment by LarsDenBakker** [comment]
LGTM as well. However since we still use lerna in this repository, we need to create a commit for each package separate. I can't do that from the git GUI unfortunately.

**Comment by abdonrd** [comment]
Why create a commit for each package separate? 🤔

**Comment by LarsDenBakker** [comment]
That's how lerna works, the commits are a trigger for cutting a release and creating a changelog.

**Comment by abdonrd** [comment]
@LarsDenBakker PR updated. Now it's right?

**Comment by LarsDenBakker** [comment]
Yep, thanks!

**Pull request merged**
