### PR TITLE
fix: fix broken links to custom-elements.json

### LINKED ISSUE #971: broken links to custom-elements.json
ben farrel reported this on slack, we have some dead links for custom-elements.json:

> this page for one: https://open-wc.org/demoing/#custom-elements-json. I clicked on the full example: https://open-wc.org/demoing/demo/custom-elements.json
> 
> Also this is dead: Base on the data in custom-elements.json we can automatically generate knobs for your stories.
>

### PR DESCRIPTION
**Pull request by bennypowers**
fixes #971

## What this PR Does:
- Add a "vuepress:copy-static" npm script to the root package, which just copies static files into "docs/.vuepress/public"
- Adds a "prevuepress:build" and "prevuepress:start" hook to run the above script
- Fix links in the READMEs

## What this PR Does Not Do:
- any kind of clever general solution for static files
 
Note to reviewers please advise if I should change the commit message.

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
Looks good to me, but it looks like you explicitly asked @thepassle and @daKmoR to take a look at it?

**Comment by bennypowers** [comment]
Yeah esp wrt the commit message

**Comment by thepassle** [comment]
I think because this is just a docs change and shouldnt release anything the commit should be `docs: fix broken links to custom-elements.json`

I'll review during lunch of later tonight

**Comment by bennypowers** [comment]
> I think because this is just a docs change and shouldnt release anything the commit should be `docs: fix broken links to custom-elements.json`
> 
makes sense, will change

**Pull request merged**
