### PR TITLE
Update componentLibraries.js

### PR DESCRIPTION
**Pull request by Marshal27**
## What I did

  1. Add `shadow-container-query-polyfill` to componentLibraries.js

### CODE REVIEW

**Review by web-padawan — COMMENTED** [review]
Thanks for the PR. It's great to see more stuff developed around Web Components 👏 
 
This looks interesting, but the section is definitely wrong as it's not a component library.
We could consider mentioning it under a different page. @daKmoR @thepassle WDYT?

**Comment by web-padawan** [comment]
@Marshal27 Added your polyfill to [Web Components bookmarks](https://webcomponents.today/polyfills-and-shims/) - see https://github.com/web-padawan/webcomponents.today/pull/38.

**Comment by Marshal27** [comment]
@web-padawan I appreciate you adding a reference to `Web Components bookmarks`. 

Regarding this PR, I took a chance by creating it, in hopes the team would route it to the appropriate place if needed. (I appreciate you doing that.)

My logic was that this list includes several UI/UX design systems, and I thought adding the polyfill here may be helpful as the polyfill could complement the implementation of those design systems if used in concert with one of them.

In the end, my goal was to bring visibility to the polyfill for those who may be interested in using it. I appreciate you, and the team, for any references you all may feel appropriate.

**Comment by Westbrook** [comment]
We don't really have a section for polyfills right now, and I;m not sure where we'd put one one or what else we'd list, so I'm gonna close this for now.

**Pull request closed without merging**
