### PR TITLE
fix(eslint-plugin-lit-a11y): add missing valid role check in `role-supports-aria-attr` rule

### PR DESCRIPTION
**Pull request by akornmeier**
## What I did

1. Fixes issue #2466

### CODE REVIEW

**Review by bennypowers — CHANGES_REQUESTED** [review]
Can you add a regression test?

**Comment by akornmeier** [comment]
> Can you add a regression test?

Yes definitely, but I was thinking of a way to do this while adhering to the current testing pattern. There are two rules that assume the use of a valid role in the package: 

1. [role-supports-aria-attr](https://github.com/open-wc/open-wc/blob/master/packages/eslint-plugin-lit-a11y/docs/rules/role-supports-aria-attr.md)
1. [role-has-required-aria-attrs](https://github.com/open-wc/open-wc/blob/master/packages/eslint-plugin-lit-a11y/docs/rules/role-has-required-aria-attrs.md)

The use of an invalid role `<div role="pizza">:pizza:</div>` would be caught by the [aria-role](https://github.com/open-wc/open-wc/blob/master/packages/eslint-plugin-lit-a11y/docs/rules/aria-role.md) rule.

What technique would be best for testing the by-pass logic in `role-supports-aria-attr` that an invalid role would not throw an exception in the DOM?

**Comment by akornmeier** [comment]
@bennypowers - Checking in after I added a regression test. Is there anything else required to get the PR merged? Thanks!

**Review by bennypowers — APPROVED** [review]

**Comment by akornmeier** [comment]
Is there an ETA on the next release?

**Comment by bennypowers** [comment]
cicd is stuck 🤦

**Comment by bennypowers** [comment]
just YOLO'd it, hopefully it won't blow up 😅

**Pull request merged**
