### PR TITLE
Fix peerDependencies in eslint-config

### LINKED ISSUE #1951: eslint-config: wrong peer dependency eslint-plugin-babel@^7.6.0
Could someone please verify if the peer dependency for @open-wc/eslint-config should be either
- `eslint-plugin-babel@^5.3.1` (by kaicataldo) or probably 
- **`@babel/eslint-plugin@^7.6.0` ?** 

My npm v7 complains:

> npm WARN Could not resolve dependency:
> npm WARN peer eslint-plugin-babel@"^7.6.0" from @open-wc/eslint-config@4.0.0
> npm WARN node_modules/@open-wc/eslint-config

### PR DESCRIPTION
**Pull request by stephenwade**
`eslint-config` should depend on `@babel/eslint-plugin`, not the legacy `eslint-plugin-babel`. This fixes install errors when using npm@7, which now automatically installs peer dependencies.

Closes #1951.

### CODE REVIEW

**Review by felixapitzsch — APPROVED** [review]
This very simple one-line change fixes the issue

**Comment by felixapitzsch** [comment]
Could someone from this project (with write access) please review and approve this PR? It is a really simple fix. However, the issue is really blocking me and my colleagues. And all other means to work around the issue are very hacky.

**Comment by thepassle** [comment]
Hrm. Looks like prettier fails on the auto generated changeset. Thats something we'll have to look into and fix, for now, could you pull and run `yarn format:prettier` from the root of the project, and commit the changes to make the CI pass?

**Review by daKmoR — APPROVED** [review]

**Comment by daKmoR** [comment]
formatted it 👍 

thank you 🤗

**Pull request merged**
