### PR TITLE
Balance brackets in code example

### PR DESCRIPTION
**Pull request by andnorda**
## What I did

1. Balanced some brackets in code example.

### CODE REVIEW

**Comment by jamiejojo** [comment]
Stop attaching me I do not know what this is I will report it to
authorities
Jamie

**Review by Westbrook — APPROVED** [review]
Thanks for catching this!!

**Comment by jamiejojo** [comment]
What did I comment out of curiosity bc it wasn’t me I’m sure my ex husband
has access to my email and I have no clue what any of rhis means
Jamie

**Comment by thepassle** [comment]
@jamiejojo If you navigate to https://github.com/open-wc/open-wc, and click on the following button: 
image

You should no longer receive updates :)

**Pull request merged**
