### PR TITLE
docs: use Rocket

### PR DESCRIPTION
**Pull request by Westbrook**
Quick and dirty to get the conversation started and confirm the CI still works, etc.

https://wip-next-open-wc.netlify.app/

Older iterations:
- https://5f64e54d6bdadd009d5634f9--open-wc-org.netlify.app

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
First outline:

# Guides
- [Getting started](https://open-wc.org/init/)
- [Codelabs](https://open-wc.org/codelabs/)
- [Code examples](https://open-wc.org/developing/code-examples.html)
- [Developing](https://open-wc.org/developing/)
- [Publishing web components](https://open-wc.org/publishing/)
- [Deploying apps](https://open-wc.org/deploying/)

# Docs
- Recommendations
  - [Best practices](https://open-wc.org/developing/best-practices.html)
  - [IDE](https://open-wc.org/developing/ide.html)
  - [Types](https://open-wc.org/developing/types.html) 
  - [WC Libs](https://open-wc.org/guide/component-libraries.html)
  - [Linting](https://open-wc.org/linting/)
    - [Eslint](https://open-wc.org/linting/linting-eslint.html)
  - [Testing](https://open-wc.org/testing/) -> Change to WTR and link to modern-web
    - [Testing library](https://open-wc.org/testing/testing.html)
  - [Building](https://open-wc.org/building/)
    - [Rollup](https://open-wc.org/building/building-rollup.html)
  - [Demoing](https://open-wc.org/demoing/)
- Libraries
  - [Lit helpers](https://open-wc.org/developing/lit-helpers.html)
  - [Dedupe Mixin](https://open-wc.org/guide/dedupe-mixin.html)
  - [Scoped Elements](https://open-wc.org/scoped-elements/)
  - [Testing helpers](https://open-wc.org/testing/testing-helpers.html)
  - [Chai a11y axe](https://open-wc.org/testing/testing-chai-a11y-axe.html)
  - [Semantic dom diff](https://open-wc.org/testing/semantic-dom-diff.html)
- Tools
  - [Storybook addon markdown docs](https://open-wc.org/demoing/storybook-addon-markdown-docs.html)

# Dropped pages
- [Karma](https://open-wc.org/testing/testing-karma.html)
- [Karma Browserstack](https://open-wc.org/testing/testing-karma-bs.html)
- [karma esm](https://open-wc.org/testing/karma-esm.html)

# Move to modern web
- [es dev server](https://open-wc.org/developing/es-dev-server.html)
- [rollup HTML plugin](https://open-wc.org/building/rollup-plugin-html.html)
- [polyfills loader plugin](https://open-wc.org/building/rollup-plugin-html.html)
- [polyfills loader](https://open-wc.org/building/polyfills-loader.html)

**Comment by Westbrook** [comment]
First pass at @LarsDenBakker's suggestion: https://5f67a513d18439d7c128a1a0--open-wc-org.netlify.app/

Maybe I missed it, but not sure how to treat:
https://5f67a513d18439d7c128a1a0--open-wc-org.netlify.app/guides/lit-html/
https://5f67a513d18439d7c128a1a0--open-wc-org.netlify.app/guides/types/
https://5f67a513d18439d7c128a1a0--open-wc-org.netlify.app/guides/testing/

**Comment by Westbrook** [comment]
Next steps here:
- Submit redirects file for use in Netlify and then we _should_ be OK for moving forward here.

**Comment by daKmoR** [comment]
pushed an update with latest rocket and quite a big restructure which you can see in action here
https://wip-next-open-wc.netlify.app/

**Comment by daKmoR** [comment]
superseeded by https://github.com/open-wc/open-wc/pull/1875

**Pull request closed without merging**
