### PR TITLE
fix(core): use types everywhere, export interfaces

### PR DESCRIPTION
**Pull request by bennypowers**

### CODE REVIEW

**Comment by bennypowers** [comment]
@dakmor check out the interface in mdjsStoryParse.js. not sure if that's an exhaustive list of properties that I derived there, and some of the unions might be unnecessarily narrow.

**Comment by LarsDenBakker** [comment]
Looks good to me

**Comment by LarsDenBakker** [comment]
Actually, can we add a `tsconfig` here like this: https://github.com/open-wc/open-wc/blob/master/packages/polyfills-loader/tsconfig.json so that we don't regress on types?

**Comment by LarsDenBakker** [comment]
@daKmoR you wanna check this?

**Comment by daKmoR** [comment]
awesome - thx 🤗

**Pull request merged**
