### PR TITLE
Remove Theme

### PR DESCRIPTION
**Pull request by stramel**
Unnecessary theme setting override

### CODE REVIEW

**Comment by web-padawan** [comment]
Was also wondering why it is there. The editor theme is just the matter of personal preference, e.g. I'm used to Monokai or similar dark variations 😃 You can refer to VSCode documentation instead.

**Comment by daKmoR** [comment]
agreed - can you sign the CLA and I will merge

**Comment by stramel** [comment]
Signed 👍🏼

**Comment by daKmoR** [comment]
thxxxx :hugs: merged :tada:

**Pull request merged**
