### PR TITLE
chore: update rollup-plugin-terser

### PR DESCRIPTION
**Pull request by abdonrd**
The v5 depends on a version of `serialize-javascript` with a vulnerability:

https://github.com/IBM/pwa-lit-template/network/alert/package-lock.json/serialize-javascript/open

Screenshot 2020-08-13 at 09 29 41

### CODE REVIEW

**Comment by abdonrd** [comment]
Depends on new relase with: https://github.com/terser/terser/pull/779

**Comment by abdonrd** [comment]
Now terser.minify is async, we need to update it.

**Comment by LarsDenBakker** [comment]
This is definitely going to be a bit of a pain to rewrite :(

**Comment by LarsDenBakker** [comment]
Thanks a lot of this PR. Upgrading terser will be a bit more complex, but I don't want to block that updating the rollup plugin so I'm doing that upgrade in https://github.com/open-wc/open-wc/pull/1831.

**Pull request closed without merging**
