### PR TITLE
fix(building-utils): check ShadyDOM.force in polyfills

### LINKED ISSUE #1070: Rendertron doesn't work with open-wc application
[Rendertron](https://github.com/GoogleChrome/rendertron) doesn't work with `open-wc` application.

You can see how the app works:
https://open-wc-starter-app.netlify.com

But Rendertron show a white screen:
https://render-tron.appspot.com/render/https://open-wc-starter-app.netlify.com

Same white screen with the `?wc-inject-shadydom=true`:
https://render-tron.appspot.com/render/https://open-wc-starter-app.netlify.com?wc-inject-shadydom=true

Any idea why it doesn't work?

### PR DESCRIPTION
**Pull request by abdonrd**
Fix #1070

Thanks to @captaincodeman and @LarsDenBakker

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
There are still some snapshots failing, did you run `yarn test:update-snapshots` at the root level? that should update all of them.

**Comment by abdonrd** [comment]
Yes, I do this on the last commit 😕

**Comment by LarsDenBakker** [comment]
I'll look into the snapshots

**Comment by LarsDenBakker** [comment]
Merging this in https://github.com/open-wc/open-wc/pull/1072

**Pull request closed without merging**
