### PR TITLE
Update eslint-config dependencies

### PR DESCRIPTION
**Pull request by abdonrd**
Update eslint-config dependencies.

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
I missed this one when I worked on https://github.com/open-wc/open-wc/pull/710. I tried updating to eslint v6, but that was giving issues for me. Does it work for you?

**Comment by abdonrd** [comment]
Updated! 🚀

**Comment by LarsDenBakker** [comment]
Of course the day after I try it, air bnb base comes out with eslint v6 support 👍

**Comment by abdonrd** [comment]
@LarsDenBakker I'm not sure why the tests fail after this PR.

**Comment by LarsDenBakker** [comment]
I think you regenerated the lockfile, which pulled in the latest versions of all dependencies. This changes the integration test snapshots, because they contain file hashes. It's a bit cumbersome, but it's a great way to ensure stability of the tools. 

I've merged your changes with https://github.com/open-wc/open-wc/pull/710 and regenerated the snapshots in https://github.com/open-wc/open-wc/pull/733 so I'll close this one.

Thanks a lot of the help, and sorry for the bumpy ride :)

**Comment by abdonrd** [comment]
Thanks @LarsDenBakker! 🙂

**Pull request closed without merging**
