### PR TITLE
test(create): add basic integration test for app with all features

### PR DESCRIPTION
**Pull request by bennypowers**
fixes: #941
closes: #970

## What this PR Does:

tests that the following command
```
node -r @babel/register packages/create/src/create.js \
  --destinationPath ./output \
  --type scaffold \
  --scaffoldType app \
  --features linting testing demoing building \
  --buildingType rollup \
  --scaffoldFilesFor testing demoing building \
  --tagName scaffold-app \
  --writeToDisk true \
  --installDependencies false
```

in fact creates the desired output files.

Each output file's content is checked against the snapshot.

## What this PR Doesn't Do:
- test any other commands
- test the wizard UI
- test the keyboard input
- provide an automated way to update the snapshots
- provide clear guidance or convention for naming snapshots based on input/test case

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
I like this. We are committing the whole generated output as a snapshot, but I think it's a nice way to keep a grasp on what the generator does and that our changes don't mess it up.

**Comment by thepassle** [comment]
I think this looks really nice :)

I wonder if it would be possible to run lint/test on the output files? It has happened in the past tht the generator runs fine and scaffolds some files, but that there was a mistake in the files (wrong import, introduced  a linting problem, etc)

if we can somehow run linting and tests we can be really confident that we didnt break anything

**Comment by bennypowers** [comment]
@thepassle I'm going to look into running the linter on the output in tests

only reason i can think of not to would be that `npm i` will be expensive in terms of CI time. we could hack around that by treating the ACTUAL test output as a package in the monorepo, for purposes of linting

**Comment by bennypowers** [comment]
@thepassle 

https://github.com/open-wc/open-wc/blob/91321f43ed939aef70a6282f4f24265b8906078c/packages/create/test/integration.test.js#L121-L126

**Comment by thepassle** [comment]
So nice 😄 Can we run tests on the output too?

**Comment by bennypowers** [comment]
> output ?
`ACTUAL_PATH` is the output, so this runs eslint programmatically on the generated files

AFAICT it's the same as `cd scaffold-app && npx eslint`

**Comment by thepassle** [comment]
? Not sure what you mean with your last comment

**Comment by bennypowers** [comment]
edited. I mean this test *does* lint the generator output

**Comment by bennypowers** [comment]
🤦‍♂ oh you mean *TESTS*

uhh yeah let me check

**Comment by bennypowers** [comment]
so, these tests run in a node context.. i suppose i could spin karma up in a child process

**Comment by bennypowers** [comment]
discussing it on slack, we agreed it's best to leave this at simple tests for now. later on we'll implement proper e2e tests that run, install, and test output in a separate ci process

**Pull request merged**
