### PR TITLE
Replace `rollup-plugin-html` with `@web/rollup-plugin-html`

### LINKED ISSUE #1980: Replace @open-wc/rollup-plugin-html with @web/rollup-plugin-html
There are any plans to replace `@open-wc/rollup-plugin-html` with `@web/rollup-plugin-html` in the `@open-wc/building-rollup`? There are interesting stuff like the `absoluteBaseUrl` there.

### PR DESCRIPTION
**Pull request by abdonrd**
## What I did

1. Replace `rollup-plugin-html` with `@web/rollup-plugin-html`
2. Also replace `babel-plugin-bundled-import-meta` with `@web/rollup-plugin-import-meta-assets`
3. Also replace `@open-wc/rollup-plugin-polyfills-loader` with `@web/rollup-plugin-polyfills-loader`

Fix #1980

Maybe related: https://github.com/open-wc/open-wc/issues/2037

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
We're planning on dropping support for IE11 in the generator, this reduced the need for a wrapper config like this one so we will ship just a plain rollup config in the generator. We can still make this change for people who still use the config though.

It looks like there are some functional errors with the integration tests, that needs to be looked into. Since you're no longer applying the babel import meta plugin, the assertions need to be updated.

**Comment by abdonrd** [comment]
Thanks @LarsDenBakker! I still have this one:

Screenshot 2021-05-19 at 14 27 16

How to deal with this ids?

**Comment by LarsDenBakker** [comment]
That'd be hard to test then, we can also skip them.

**Comment by abdonrd** [comment]
@LarsDenBakker updated! Now just one test failing 😕 

https://github.com/open-wc/open-wc/pull/2213/checks?check_run_id=2641928407#step:7:175

**Comment by abdonrd** [comment]
Maybe related: https://github.com/open-wc/open-wc/issues/2037

**Comment by LarsDenBakker** [comment]
@abdonrd you replaced babel-bundled-import-meta with `@web/rollup-plugin-import-meta-assets` so the test assertions need to be updated accordingly. I'll pull this branch and make the changes

**Comment by abdonrd** [comment]
Replaced by #2228

**Pull request closed without merging**
