### PR TITLE
feat(eslint-config): add eslint-plugin-lit

### PR DESCRIPTION
**Pull request by LarsDenBakker**
This adds eslint-plugin-lit, except for tests and demos where we sometimes want to do funky things.

This is technically a breaking change, that's convenient for some and inconvenient for others. What do you guys think?

Fixes https://github.com/open-wc/open-wc/issues/912

### CODE REVIEW

**Comment by thepassle** [comment]
LGTM, how should we go about the breaking change?

**Comment by LarsDenBakker** [comment]
It should be in the commit message, @daKmoR double check if I formatted the message correctly? :)

**Comment by thepassle** [comment]
according to conventional commits there needs to be a colon after `BREAKING CHANGE`: https://www.conventionalcommits.org/en/v1.0.0-beta.4/

im not sure if it matters though 🙈

**Comment by LarsDenBakker** [comment]
Let's change the message to that when we squash the commits. I need someone to approve the PR though :)

**Pull request merged**
