### PR TITLE
#616 Update building tools with `main` entry point.

### PR DESCRIPTION
**Pull request by Westbrook**
- adds `main` to rollup
- add `main` to webpack
- **asks** for naming approval

TO DO:
- [ ] add usage in the generator for rollup
- [ ] add usage in the generator for webpack

### CODE REVIEW

**Comment by daKmoR** [comment]
looks good to me (including the names) 👍 

before merging we should update the readmes - generators can/should be done afterwards (as you can't properly test it before it's released)

**Comment by LarsDenBakker** [comment]
Looks great! Should we maybe rename createConfig to createDefaultConfig? Im doubting a bit.

Can you name the main entry point after the package name for consistency?

**Comment by LarsDenBakker** [comment]
We probably need to update the readme as well

**Comment by Westbrook** [comment]
Updated the naming here and expanded the docs.

If we're good on the naming, I've got some generator additions that I can push up as well!

**Comment by LarsDenBakker** [comment]
Looks good to me!

**Comment by daKmoR** [comment]
woop woop 🎉

**Pull request merged**
