### PR TITLE
docs: Add Simplr Router to recommended routers

### PR DESCRIPTION
**Pull request by Matsuuu**
I have a created a light router for SPA -type applications built with Web Components. 

I would be honored if I could get it added to the list of routers for web component development.

### CODE REVIEW

**Comment by thepassle** [comment]
Hi! Sorry, I somehow missed this PR. The router looks good, but do you intend to write tests for it?

**Comment by Matsuuu** [comment]
@thepassle No problem. I am in the plans of writing tests for it, yes. 

Would you have any recommendations on a tool to write them in? Mostly done unit tests in Java so what would you suggest for javascript testing?

**Comment by Matsuuu** [comment]
Hi again @thepassle . I have now implemented unit tests for the router, and reached 94% coverage. There are a couple of things that were not (at least in normal means) testable with jest, so that's why the 6% is missing.

I hope this is enough for the request to be accepted

**Comment by thepassle** [comment]
Hi Matsuu, thanks! Looks good :) One small final nitpick: the list is ordered alphabetically, could you place Simplr between redux and vaadin router? Happy to merge then :)

**Comment by Matsuuu** [comment]
Ahh, that totally makes sense. Fixed the list to a alphabetical order now. :)

**Comment by thepassle** [comment]
@Matsuuu Thanks for your contribution!

**Pull request merged**
