### PR TITLE
docs: review scoped elements docs

### PR DESCRIPTION
**Pull request by thepassle**

### CODE REVIEW

**Comment by manolakis** [comment]
Looks good to me.

@thepassle @daKmoR do you mind if I merged it and squash the commits to fix the commitlint?

**Comment by thepassle** [comment]
Ah yes, it looks like I messed the commit up. I also see there are now merge conflicts

**Comment by thepassle** [comment]
@manolakis It would maybe have been good to first merge this before making the docs changes in your branch 😅

**Comment by manolakis** [comment]
>@manolakis It would maybe have been good to first merge this before making the docs changes in your branch 😅
Yes, sorry! 😞

**Pull request merged**
