### PR TITLE
Fix/lit a11y/anchor is valid/permit hash

### PR DESCRIPTION
**Pull request by bennypowers**
follows on from #1915 by adding helpers for checking attributes and expressions

permits `<a href="#">`

blocked by #1917

### CODE REVIEW

**Comment by thepassle** [comment]
should we merge this into #1917 and then merge that to master? it gets kinda hard to see what has changed

**Comment by thepassle** [comment]
also gotta run prettier to make pipeline pass

**Comment by bennypowers** [comment]
closing in favour of #1917

**Comment by thepassle** [comment]
I meant just change the target branch to be #1917 instead of master 🙈 because the changes in #1917 are a lot, so it makes it hard to see what exactly is going on and what has changed

**Comment by bennypowers** [comment]
🤦‍♂️ whoopsie

**Pull request closed without merging**
