### PR TITLE
WIP: feat(building-utils): adds support for the custom-styles polyfill

### PR DESCRIPTION
**Pull request by jrobinson01**
Adds support for the custom-styles-interface polyfill. The polyfill enables using a `<custom-style>` element wrapped around an arbitrary `<style>` element. This is usually used to provide a theme for your app, by way of css variables. This is needed to support css variables in IE11.

### CODE REVIEW

**Comment by jrobinson01** [comment]
This will probably need a few changes once this PR lands: https://github.com/webcomponents/polyfills/pull/206

**Comment by daKmoR** [comment]
webcomponentsjs PR got merged :) so does this need an update now?

**Comment by jrobinson01** [comment]
Yep! I’ll get it to it tonight hopefully.

**Comment by jrobinson01** [comment]
This should be good to go, but I'm waiting on the polymer team to publish the shady-css-scoped package to npm.

**Comment by daKmoR** [comment]
still not published? 😅

**Comment by jrobinson01** [comment]
Still not published. 🙁

**Comment by daKmoR** [comment]
any luck by now? 😅

**Comment by jrobinson01** [comment]
nope. Apparently the tests weren't up to snuff and were blocking the release. There's a new PR to fix that: https://github.com/webcomponents/polyfills/pull/221

**Comment by LarsDenBakker** [comment]
Adding WIP until it's ready

**Comment by LarsDenBakker** [comment]
Closing this to keep the PR lane clean, but definitely still want this in so just reopen when it's ready. Otherwise let's publish it in a separate package to keep things moving.

**Pull request closed without merging**
