### PR TITLE
Update Storybook addon metadata

### PR DESCRIPTION
**Pull request by coderkevin**
Hey open-wc! We've created a catalog of Storybook addons and yours is included: https://storybook.js.org/addons/storybook-addon-markdown-docs

To make your addon more discoverable in the catalog, we've curated some of its metadata, and I've included those edits in this PR.

To learn more about the catalog metadata, check out our documentation: https://storybook.js.org/docs/react/addons/addon-catalog

### CODE REVIEW

**Comment by stephenwade** [comment]
Please move `keywords` above `dependencies`. That will satisfy Prettier and should make this pass CI.

**Comment by Westbrook** [comment]
It's also likely that `yarn format:prettier` would put the order down correctly as well.

**Comment by coderkevin** [comment]
I just got back from a trip. I'll update soon. Thanks!

**Comment by coderkevin** [comment]
Thanks!

**Pull request merged**
