### PR TITLE
fix(building-rollup): Add missing dependency

### PR DESCRIPTION
**Pull request by Pupix**

### CODE REVIEW

**Comment by Pupix** [comment]
Welp I borked the commit message.

**Comment by thepassle** [comment]
Could you check if this needs to be done in the generator as well? Id like to keep everything in sync :)

**Comment by Pupix** [comment]
The generator uses the `building-rollup` package directly https://github.com/open-wc/open-wc/blob/aa3018db055e138830b8ff6fc31b26f3cff2fbbd/packages/create/src/generators/building-rollup/templates/_package.json#L8 so it should inherit the change without modifying anything.

**Comment by thepassle** [comment]
Oki, just making sure. Thanks! LGTM.

I can't merge, @daKmoR  ?

**Comment by LarsDenBakker** [comment]
What is clone used for? I dont see it used.

**Comment by LarsDenBakker** [comment]
Oh its in the dom5 fork .

**Pull request merged**
