### PR TITLE
Remove `git add` from example `lint-staged` task

### PR DESCRIPTION
**Pull request by danielmatthew**
The `lint-staged` task complains at `git add`, stating that it performs this action automatically.

### CODE REVIEW

**Comment by daKmoR** [comment]
looks good - you can ignore the commit lint but the CLA I need you to sign 😅

**Comment by danielmatthew** [comment]
@daKmoR Of course – I did want to pad out the PR description a touch more, but it's getting late.

Thanks for the quick response!

**Comment by danielmatthew** [comment]
I've been thinking about this. 

At the time, I hadn't used the generator which adds the superfluous `git add` command to the `lint-staged` task. I guess if I remove this here, the code and documentation will become out of step. 

Would anybody object if I make the change within this PR?

**Comment by LarsDenBakker** [comment]
@danielmatthew you can change the PR, that's no problem. What changes do you want to make here?

**Comment by danielmatthew** [comment]
@LarsDenBakker Great! In my first commit, I'd only amended the docs themselves. I realised I should then update the configuration to remove the `git add` command.

**Pull request closed without merging**
