### PR TITLE
feat: add eslint-plugin-lit-a11y

### PR DESCRIPTION
**Pull request by thepassle**
# eslint-plugin-lit-a11y

Initial setup for `eslint-plugin-lit-a11y`

Just putting this up here to allow for contributions to happen. If you're interested in contributing, please create PRs to `feat/eslint-plugin-lit-a11y` (this branch) so we can gather everything together. 🙂

### Rules

<details>
<summary>You can find a list of to-be-implemented rules here:
</summary>

You can take the implementations of [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) as an example.

- [x] alt-text
- [x] accessible-emoji
- [x] anchor-has-content
- [x] anchor-is-valid
- [x] aria-activedescendant-has-tabindex
- [x] aria-props
- [x] ~~aria-proptypes~~ -> aria-attr-types
- [x] aria-role
- [x] aria-unsupported-elements
- [x] autocomplete-valid
- [x] click-events-have-key-events
- [ ] control-has-associated-label
- [x] heading-has-content
- [x] iframe-has-title
- [x] img-redundant-alt
- [ ] interactive-supports-focus
- [ ] label-has-associated-control
- [ ] label-has-for
- [ ] media-has-caption
- [x] mouse-events-have-key-events
- [x] no-access-key
- [x] no-autofocus
- [x] no-distracting-elements
- [ ] no-interactive-element-to-noninteractive-role
- [ ] no-noninteractive-element-interactions
- [ ] no-noninteractive-element-to-interactive-role
- [ ] no-noninteractive-tabindex
- [x] no-onchange
- [x] no-redundant-roles
- [ ] no-static-element-interactions
- [x] role-has-required-aria-props
- [x] role-supports-aria-props
- [x] scope
- [x] tabindex-no-positive
</details>

### Adding a new rule

Add a new rule by running:
```bash
git checkout feat/eslint-plugin-lit-a11y
cd packages/eslint-plugin-lit-a11y
npm i -g yo generator-eslint
yo eslint:rule
```

### Implementing a new rule

Implementing rules is made possible by the TemplateAnalyzer from [eslint-plugin-lit](https://www.npmjs.com/package/eslint-plugin-lit). You can take the implementations of [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) as an example.

Here's an example of a simple rule:

```js
return {
  TaggedTemplateExpression: (node) => {
    // 1. only target html`` tagged template literals
    if (node.type === 'TaggedTemplateExpression' &&
      node.tag.type === 'Identifier' &&
      node.tag.name === 'html') {
      
      // 2. create a TemplateAnalyzer and pass it the node
      const analyzer = TemplateAnalyzer.create(node);

      // 3. traverse DOM elements in the html tagged template literal
      analyzer.traverse({
        enterElement: (element) => {
            // 4. implement rule
            if ('autofocus' in element.attribs) {
              const loc = analyzer.getLocationForAttribute(element, 'autofocus');
              context.report({
                  loc,
                  message: 'Enforce that autofocus attribute is not used on elements.',
              });
            }
          }
        });
      }
    }
  }
```

### Testing a rule

In order to test a rule, you need to pass some options to the `RuleTester` to be able to support tagged template literals.

```js
var ruleTester = new RuleTester({
  parserOptions: {
  sourceType: 'module',
  ecmaVersion: 2015
}});
```

### Running tests

Clone the open-wc repo, and run `yarn` from the project root.

Then `cd` into `packages/eslint-plugin-lit-a11y` and run `npm test`

### CODE REVIEW

**Comment by bennypowers** [comment]
@thepassle can you put up a checklist of rules you'd like to see implemented, and people can track which they want to take on in the comments

**Comment by thepassle** [comment]
not stale, continuing work on this soon

**Comment by bennypowers** [comment]
I'm going to grab `control-has-associated-label`

**Comment by bennypowers** [comment]
Most of the type errors we're seeing in CI should be fixed by rebasing the target (`feat/eslint-plugin-lit-a11y`).
One of them is related to https://github.com/A11yance/aria-query/pull/74

**Review by bennypowers — APPROVED** [review]

**Pull request merged**
