### PR TITLE
fix(testing-helpers): correct type error for getScopedElementsTemplate

### LINKED ISSUE #2314: [@open-wc/testing-helpers]: no exported member getScopedElementsTemplate
When trying to setup a freshly generated project, I get an error during `npm install`.

## Expected behavior

I would expect `@open-wc/testing-helpers` to install cleanly without issues.

## Actual Behavior

```sh
$ npm i

> foo-bar@0.0.0 prepublish
> tsc && npm run analyze -- --exclude dist

node_modules/@open-wc/testing-helpers/types/src/litFixture.d.ts:10:209 - error TS2694: Namespace '"/**/foo-bar/node_modules/@open-wc/testing-helpers/types/src/scopedElementsWrapper"' has no exported member 'getScopedElementsTemplate'.

10 export function litFixtureSync<T extends Element>(template: LitHTMLRenderable, options?: import('./fixture-no-side-effect.js').FixtureOptions, getScopedElementsTemplate?: import('./scopedElementsWrapper.js').getScopedElementsTemplate): T;
                                                                                                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

npm ERR! code 1
npm ERR! path /**/foo-bar
npm ERR! command failed
npm ERR! command sh -c tsc && npm run analyze -- --exclude dist

npm ERR! A complete log of this run can be found in:
npm ERR!     /**/.npm/_logs/2021-10-02T19_01_40_131Z-debug.log
```

## Additional context

```sh
$ npm init @open-wc
```

Choices
- What would you like to do today? > Scaffold a new project
- What would you like to scaffold? > Web Component
- What would you like to add? > Linting, Testing, Demoing
- Would you like to use typescript? > Yes
- Do you want to write this file structure to disk? > Yes
- Do you want to install dependencies? > No

```sh
$ npm version
{
  npm: '7.24.1',
  node: '14.17.6',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```

```sh
$ tsc --version
Version 4.4.3
```

`@open-wc/testing-helpers: 2.0.0-next.2`

### PR DESCRIPTION
**Pull request by JackWolfard**
## What I did

1. Add `ScopedElementsTemplateGetter` type for dynamic scoped getter `getScopedElementsTemplate`

fixes #2314

### CODE REVIEW

**Comment by Westbrook** [comment]
Generally looks good to me. However, @daKmoR is the types in JSDOC guru here. Thought?

**Comment by JackWolfard** [comment]
There is the possibility to add a future test to eliminate type error issues. Ideally, this test would rely just on the `.d.ts` files.

Here is one I designed which fails for the original implementation but passes for the new one.

```ts
import './types/index.d.ts'
```

However, this would require some engineering effort to integrate this as the last step in `yarn run types`.

**Comment by manolakis** [comment]
I'm with @Westbrook. Code looks good to me, but I'm not jsdoc types expert. It would be great to have to test types.

**Review by Westbrook — APPROVED** [review]
Approving to move into pre-release for easier testing. Thanks!

**Pull request merged**
