### PR TITLE
Fix links in docs/guide readme

### PR DESCRIPTION
**Pull request by cnagadya**
The _Available Recommendations_, _Our Philosophy_ and _FAQs_ links in the docs/guide [readme](https://github.com/open-wc/open-wc/tree/master/docs/guide) are currently returning 404 since relative links[ point to the branches root directory](https://github.blog/2013-01-31-relative-links-in-markup-files/)

### CODE REVIEW

**Comment by cnagadya** [comment]
Nice catch @daKmoR. Any ideas on how to make the relative links work in markdown then?

**Comment by LarsDenBakker** [comment]
@daKmoR is this correct now?

**Comment by LarsDenBakker** [comment]
@daKmoR ?

**Comment by daKmoR** [comment]
last I checked it was still not working 🙈

we probably need
1. use the path that works for GitHub
2. add a custom script which modifies the links before netlify deploys the site

**Pull request closed without merging**
