### PR TITLE
chore: new website using rocket

### PR DESCRIPTION
**Pull request by daKmoR**
## What I did:

1. start new site using rocket

Preview URL: https://deploy-preview-1875--open-wc-org.netlify.app/

TODO:
- [x] Write Guides or hide them
- [x] Handle code labs
- [x] Copy (some) blog posts in
- [x] Check everything
- [x] (optional) Add a blog post about all the changes [potentially a separate PR for later]

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
I pushed a bunch of updates and pages. As far as I can tell the only thing remaining is adding the `:` separator between the group name and the page title. Do you think there is anything else @daKmoR ?

**Comment by daKmoR** [comment]
initial docs page might still need some love
https://deploy-preview-1875--open-wc-org.netlify.app/docs/

but it's not super important imho

**Comment by LarsDenBakker** [comment]
I added a tiny bit more to the docs main page. Not sure what else to add there at the moment, I'd say it's good enough for now. On modern-web we have a duplicate of the navigation but that quickly gets out of date (it already is actually...).

**Comment by daKmoR** [comment]
Maybe we can find some more communities?
https://deploy-preview-1875--open-wc-org.netlify.app/guides/community/getting-started/

**Pull request merged**
