### PR TITLE
fix(generate): align versions in package.json template

### PR DESCRIPTION
**Pull request by sergicontre**
Align versions for dependencies in package.json template:
lit-html
lit-element
es-dev-server

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
Looks like we missed this one, sorry about that. Unfortunately, the versions got updated again by now. It's hard to keep these things in sync, we should automate this somehow. Going to open an issue for that.

**Comment by sergicontre** [comment]
No problem. Thanks!

**Comment by bennypowers** [comment]
commit message should start with `fix(create)`. If still relevant, please update.

**Comment by LarsDenBakker** [comment]
I updated the commit message and merged it in https://github.com/open-wc/open-wc/pull/1165 (original commit author is still on your name).

**Pull request closed without merging**
