### PR TITLE
chore: run yarn-deduplicate command

### PR DESCRIPTION
**Pull request by web-padawan**
TIL about [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) tool, so here is a PR with some `yarn.lock` cleanup.

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
Thanks, looks pretty useful. We did some big changes on master now, so there are conflicts. Is this something in yarn itself, or is it a separate project?

**Comment by web-padawan** [comment]
@LarsDenBakker rebased and force-pushed. 

This is a separate tool by Atlassian, not part of yarn itself. You can run it like this:

```
npx yarn-deduplicate yarn.lock
```

**Comment by LarsDenBakker** [comment]
Unfortunately it's causes a change in snapshots, we have file hashes in snapshots which is pretty cumbersome. Looking to get red of it.

**Comment by LarsDenBakker** [comment]
I ran the tool, did some cleanup and updates the snapshots in https://github.com/open-wc/open-wc/pull/1509

Will close hthis one, Thanks for the tip!

**Pull request closed without merging**
