### PR TITLE
fix(building-rollup): support windows file paths

### PR DESCRIPTION
**Pull request by datori**
Same fix to the same issue as in #344, except for the rollup build process as well.

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
Thanks for this! Can you run `yarn format` from the root of the project? That should get the CI passing!

**Comment by datori** [comment]
Sorry about that, should be good now!

**Comment by daKmoR** [comment]
awesome 🤗 thank you for your contribution ❤️

**Comment by ggriffithsIDBS** [comment]
I literally just ran into this issue :D

**Comment by daKmoR** [comment]
there we go 🤗 
luckily @datori already solved it for you/us - I love the power of an open source community 😍

**Pull request merged**
