### PR TITLE
feat(create): building-rollup generator

### PR DESCRIPTION
**Pull request by mario-aleo**
Related to: #279

### CODE REVIEW

**Comment by daKmoR** [comment]
thx :)
all the symlinks in the docs folder probably don't need to change... (but I can just ignores these changes)

I am currently not in front of a computer.. so I will take a look the day after tomorrow :)

**Comment by daKmoR** [comment]
thaaankkk you for your contribution ❤️

**Comment by mario-aleo** [comment]
I'm really happy that I could help with something, I'm looking forward to keeping helping with anything that I can :D

**Comment by daKmoR** [comment]
awesome :) there is still toons of work to do :p

especially the generators... there is the idea to make it a real separate product; rollup should become the default building generator; also the starter app should adopt it...

the dom compare could use some slimming down as it uses htmlparser2 and parse5 (e.g. pick one)

besides that looking at issues and checking what's needed...

sooo if you wanna pick something would be awesome... and if you need any more info just let us know here or in slack :)

**Pull request merged**
