### PR TITLE
fix(es-dev-server): remove extra babel plugins

### PR DESCRIPTION
**Pull request by bennypowers**
https://github.com/babel/babel/pull/10811 was merged and released in babel 7.8.0

Fixes https://github.com/open-wc/open-wc/issues/1295

### CODE REVIEW

**Comment by bennypowers** [comment]
Does this also require a babel version bump to 7.8.0?

**Comment by LarsDenBakker** [comment]
@bennypowers yes

**Comment by bennypowers** [comment]
does that make this a major version?

**Comment by LarsDenBakker** [comment]
I don't think so, it's a dependency update but not a breaking dependency update. If you install the latest es-dev-server, you get the new version of babel too (because we bumped the version in the package.json).

**Comment by bennypowers** [comment]
NB: changed the commit types to `chore`,

**Comment by bennypowers** [comment]
Test failures related to edgium?

**Comment by LarsDenBakker** [comment]
No the babel transform tests are failing now

**Comment by abdonrd** [comment]
@LarsDenBakker now in the new `v1.38.0`, I get this error:

>page-user.ts:149 Uncaught (in promise) SyntaxError: Unexpected token '.'

And this line is an optional chaining.

**Pull request merged**
