### PR TITLE
feat(building-rollup): allow customizing sw name

### PR DESCRIPTION
**Pull request by thepassle**
closes https://github.com/open-wc/open-wc/issues/1737

### CODE REVIEW

**Comment by thepassle** [comment]
Hm, pipeline says no:

```
packages/building-rollup/src/createSpaConfig.js:33:27 - error TS2339: Property 'swDest' does not exist on type 'true'.
 

 
33       userOptions.workbox.swDest &&
 
                             ~~~~~~
 
```

even though `workbox` is:
```
  workbox?: boolean | object;
```

🤔 Any ideas?

**Comment by bennypowers** [comment]
Should probably type the `object` side of the union with the actual options type

**Comment by thepassle** [comment]
That gives me:
```
export interface SpaOptions extends BasicOptions {
  html?: boolean | object;
  polyfillsLoader?: boolean | object;
  workbox?: boolean | WorkboxOptions;
  injectServiceWorker?: boolean;
}

interface WorkboxOptions {
  swDest: string
}
```

```
Property 'swDest' does not exist on type 'true | (false & WorkboxOptions) | (true & WorkboxOptions)'.
  Property 'swDest' does not exist on type 'true'.ts(2339)
```

I think it might be inferring the type from a bit up in the `createSpaConfig` on line 19:
```js
  const userOptions = merge(
    {
      html: true,
      polyfillsLoader: true,
      workbox: true,
      injectServiceWorker: false,
    },
    options,
  );
```

**Comment by abdonrd** [comment]
Ops! This PR as is, breaks this template: https://github.com/IBM/pwa-lit-template/pull/44

**Comment by thepassle** [comment]
Sorry @abdonrd! Just made a PR to fix it

**Pull request merged**
