### PR TITLE
fix(deps): update rollup-plugin-workbox to v6

### PR DESCRIPTION
**Pull request by stephenwade**
## What I did

1. Updated rollup-plugin-workbox to v6 which uses Workbox v6

### CODE REVIEW

**Comment by stephenwade** [comment]
I'm not sure if this should be a minor or major change. I'm happy to update the changeset to cut a major release if that is desired.

**Comment by thepassle** [comment]
Thanks for the PR!

This does look like it would be a major change, since a couple of things in workbox have changed. If we're going to do a major, I'd like to check with the others if there's anything we should update as well, maybe https://github.com/open-wc/open-wc/pull/1986 ?

cc @LarsDenBakker @daKmoR @Westbrook @bennypowers

**Comment by LarsDenBakker** [comment]
Yes we should combine it with the HTML plugin update. I haven't had any time to look into the issues that are stalling that PR

**Comment by stephenwade** [comment]
@thepassle I updated the changeset to be major.

**Comment by abdonrd** [comment]
Waiting for this, thanks! 👏🏻

**Comment by stephenwade** [comment]
Not stale. Waiting for #2213.

**Comment by abdonrd** [comment]
Any news about this?

**Comment by LarsDenBakker** [comment]
This one got merge conflicts, I created https://github.com/open-wc/open-wc/pull/2236 without conflicts. As with the PR, I'm very sorry this took way to long to get merged...

**Comment by stephenwade** [comment]
Replaced by #2236.

**Pull request closed without merging**
