### PR TITLE
chore: let prettier handle *.md files

### PR DESCRIPTION
**Pull request by Ania-chan**
## Description

I've set up markup linter in a same way as in this PR: https://github.com/ing-bank/lion/commit/c23fc22061678bc9b70e2c0ad5a56aee6e94afc2 
In .editorconfig I've only set rules related to markdown.
Please let me know if you'd like to add or change any of the rules!

## Issue
#826

### CODE REVIEW

**Comment by Ania-chan** [comment]
@daKmoR Hi! I made a PR but I'm failing CircleCI tests because of the markdown linting errors.
Also I'm a bit worried about the fact that after installing `markdownlint-cli` this part of yarn lock got changed: 
Screen Shot 2019-10-02 at 20 03 16
Do you know if it's a problem?

Let me know if there is anything I need to change!

**Comment by daKmoR** [comment]
hey that looks really nice :)

the changes to the yarn lock are fine 👍 

would be really cool to have 2 commits
1. `chore: setup markdown linting`
2. `chore: apply markdown linting to all files` (basically `npm run format` with markdown formatting setup and commit all the changes)

if you need any help making this just let me know :) if you are on slack feel free to ask me directly if not I will do my best to answer in a more timely manner 🤗 

PS: files in `__snapshots__` will need to be excluded as well 🤗

**Comment by Ania-chan** [comment]
@daKmoR Thanks for the feedback! I'll try squashing my commits and than I'll format the markdown files. I'll let you know if I have any problems :)

**Comment by Ania-chan** [comment]
@daKmoR Hi! I squashed my previous commits into one but now I'm stuck in the second commit. I have trouble creating script that automatically fixed .md files and also excludes `__snapshots__` 😞 Where can I contact you on slack?

**Comment by daKmoR** [comment]
see the contact section in the readme
https://github.com/open-wc/open-wc/blob/master/README.md#contact

the open-wc on slack is where the most of us are 🤗

**Comment by Ania-chan** [comment]
Hi @daKmoR! 
I changed the script to ignore `__snapshots__` folder. Unfortunately I think that at the moment `markdownlint` doesn't have functionality to auto format files: https://github.com/igorshubovych/markdownlint-cli/issues/59

Current script for prettier `"format:prettier": "prettier \"**/*.{js,md}\" --write",` is auto formatting markdown files as well but it uses different rules than `markdownlint`. There is also this VS Code that can be used to auto format: 
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
What do you think?

**Comment by daKmoR** [comment]
@Ania-chan thank you for this :)

Yes you are totally right - prettier alone is good enough for us 🤗 so I removed markdownlint and added another commit on top applying prettier to all files 🤗

**Pull request merged**
