### PR TITLE
feat(create): move to a single app generator

### PR DESCRIPTION
**Pull request by thepassle**

### CODE REVIEW

**Comment by thepassle** [comment]
To do: fix className to tagName in storybook -> index.stories.js

https://polymer.slack.com/archives/CE6D9DN05/p1563341672214000

**Comment by LarsDenBakker** [comment]
Looking good... some thoughts:

Should we add a `(recommend)` marker behind the recommended options. For example rollup over webpack?

Should we add a 'pick all defaults' option?

**Comment by daKmoR** [comment]
if we have more then one option adding a `(recommend)` seems like a good approach... we only have it for building right?

**Comment by thepassle** [comment]
If we add a ‘pick all defaults’ option that basically leads to having a starter-app again though :p

**Comment by LarsDenBakker** [comment]
Hehe yes I understand the irony there. Maybe I was just slow, but I didn't understand that difference in the current setup. Saying that it's the setup with all defaults makes it clear I think, and we can add it for both apps and components.

**Pull request merged**
