### PR TITLE
fix: improve clarity of init

### PR DESCRIPTION
**Pull request by thepassle**
Fixes https://github.com/open-wc/open-wc/issues/429

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
I see now that basic app doesnt come with any build/test etc. Whats the point then?

**Comment by thepassle** [comment]
Its easy for quick prototyping I guess, also works nicely when using with pika cdn, though I add it manually. I use the barebone app quite a lot actually. Maybe also interesting with the import maps stuff coming up?

**Comment by LarsDenBakker** [comment]
Ah I see. I feel that it adds a lot of confusion though. Starter app gives you choices, right? You could toggle everything off?

**Comment by thepassle** [comment]
Thats true yeah. In that case it may be fine to get rid of it, it made more sense to have it before we had the option toggles in the cli. Im fine with removing it, dont know if master chief @dakmor has any strong feelings about it?

**Comment by LarsDenBakker** [comment]
I'll merge this now, we should revisit the init later.

**Comment by thepassle** [comment]
Yeah we should iron it out a bit more. Im fairly occupied this week (buying a house/moving), so maybe the week after we can have a discussion about it.

I think the starter-app should go. The ‘Application’ without anything selected is basically the ‘Barebones app’ and with everything selected its just the ‘Starter App’. But lets have a chat and make sure.

**Pull request merged**
