### PR TITLE
fix(webpack-import-meta-loader): rewrite all backslashes

### PR DESCRIPTION
**Pull request by LarsDenBakker**
Fixes https://github.com/open-wc/open-wc/issues/476

### CODE REVIEW

**Comment by tmsns** [comment]
Wanted to add a specific test for it:

```
  it('Replaces all backslashes', async () => {
    const stats = await compiler('caseB\\caseBsub\\caseBsub.js', rules);
    const caseBsub = stats.toJson().modules[0].source;

    expect(caseBsub).to.equal(
      `${'' +
        "export const bar = new URL('./', ({ url: `${window.location.protocol}//${window.location.host}/caseB/caseBsub/caseBsub.js` }).url);"}${newLine}`,
    );
  });
```

But Karma doesn't want to find the test. I did see the exclusion in the Karma config [karma.conf.js#L13](https://github.com/tmsns/open-wc/blob/master/karma.conf.js#L13), but also the with grep function, I can't find it.. :-/
`yarn run test --grep packages/webpack-import-meta-loader/test/webpack-import-meta-loader.test.js`

**Comment by LarsDenBakker** [comment]
These tests are run in node, not in in the browser. That's why they're excluded. You can run them by moving into the `packages/webpack-import-meta-loader` and running `npm run test` or `yarn test`

**Comment by tmsns** [comment]
> These tests are run in node, not in in the browser. That's why they're excluded. You can run them by moving into the `packages/webpack-import-meta-loader` and running `npm run test` or `yarn test`

😅 🙈 God... I guess it's been a long day..

**Comment by tmsns** [comment]
Hmmm.. ok.. The test is not working how I expected it to work. `compiler` is using webpack, so backslashes are already transformed in the tests. Don't know if it'll be doable to test the specific behavior. 🤔 

On a sidenote, by using `import { EOL as newLine } from 'os';` the test expects the files to be using the specific EOL chars of the system. I'm using git's `core.autocrlf=false` so no auto conversion.. hence, breaking tests. 🙈

**Comment by LarsDenBakker** [comment]
Does the change work properly for you locally though? Will look into a proper setup for testing these things cross platform later.

**Comment by tmsns** [comment]
Normally yes, as I tested the `/\\/g` variant earlier today by changing it in `node_modules` directly. So, I expect it to work just fine. 👍

**Comment by LarsDenBakker** [comment]
Made a test and checked with @thepassle that it's working

**Comment by tmsns** [comment]
Yeah, the mocked `path` module will do the trick! Of course, there is no guarantee that `toBrowserPath` is actually used in the plugin, but it's always tricky when using mocks. [proxyquire](https://www.npmjs.com/package/proxyquire) seems to be helpful.

**Pull request merged**
