### PR TITLE
Feat/add browsersync

### PR DESCRIPTION
**Pull request by thepassle**
closes https://github.com/open-wc/open-wc/issues/363

### CODE REVIEW

**Comment by thepassle** [comment]
I guess the dependency isnt safe. :/

**Comment by LarsDenBakker** [comment]
I think this is a good addition. Whats the runtime overhead? As far as I can tell browser sync does a lot more than just reloading, for example also it syncs scrolling across tabs/browsers.

**Comment by thepassle** [comment]
connect-browser-sync adds 8.4kb and browser-sync surprisingly doesnt have a rating on bundlephobia 🤔

**Comment by thepassle** [comment]
@daKmoR can you see in snyk what the problem exactly is? I have no access: `Unable to display this organisation
The organisation does not exist, or you do not have permissions to access it.
`

**Comment by thepassle** [comment]
closing in favor of #447

**Pull request closed without merging**
