### PR TITLE
feat(es-dev-server): enable compression

### LINKED ISSUE #723: [es-dev-server] Enable file compression
Can you enable file compression to know the actual transferred data in browser and better performance

### PR DESCRIPTION
**Pull request by bennypowers**
affects: es-dev-server

closes #723

### CODE REVIEW

**Comment by bennypowers** [comment]
note this uses the koa-compress default threshold of 1kb, but can be configured by passing a koa-compress options object instead of `true` as the `compress` config item.

```js
createConfig({ compress: { threshold: 1 } });
```

**Comment by LarsDenBakker** [comment]
Do you think turning this on by default will speed things up locally?

**Comment by bennypowers** [comment]
Not necessarily, but as mentioned in the issue, since it's best practice, and cheap to enable, (and for other reasons cited there) we might as well.

**Comment by daKmoR** [comment]
@LarsDenBakker please check and give 👍  or 👎  for using compress by default

**Comment by LarsDenBakker** [comment]
Lets do compression by default

**Pull request merged**
